# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

let
  cfg = config.tartelette.mountHDD;
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  options.tartelette.mountHDD = lib.mkOption {
    type = lib.types.bool;
    default = true;
    description = "" "\n    Whether to mount the HDD's partitions.\n    Disabled on the SD card image, because the store on the HDD might not have been created yet.\n    " "";
  };

  config = {

    fileSystems = lib.mkIf cfg {

      "/" = {
        device = "/dev/disk/by-label/main";
        fsType = "ext4";
        neededForBoot = true;
      };

      "/home/hugobd/syncthing" = {
        device = "/dev/disk/by-label/syncthing";
        depends = [ "/home/hugobd" ];
        fsType = "ext4";
      };

    };

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

    powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";

  };
}
